### ISSUE TITLE
Browser responsive

### ISSUE THREAD

**Issue by jamilcse13** [slawomir-zaziablo/range-slider#12]
How to make this slider browser responsive? The number breaks the line while using the various browsers.

**Comment by FelipeSanchezCalzada** [comment]
Only need to add:
```css
.rs-container .rs-scale span:last-of-type {
  width: 0 !important;
}
```
